whisper_compatible = [
    "afrikaans",
    "albanian",
    "amharic",
    "arabic",
    "armenian",
    "assamese",
    "azerbaijani",
    "bashkir",
    "basque",
    "belarusian",
    "bengali",
    "bosnian",
    "breton",
    "bulgarian",
    "burmese",
    "castilian",
    "catalan",
    "chinese",
    "croatian",
    "czech",
    "danish",
    "dutch",
    "english",
    "estonian",
    "faroese",
    "finnish",
    "flemish",
    "french",
    "galician",
    "georgian",
    "german",
    "greek",
    "gujarati",
    "haitian",
    "haitian creole",
    "hausa",
    "hawaiian",
    "hebrew",
    "hindi",
    "hungarian",
    "icelandic",
    "indonesian",
    "italian",
    "japanese",
    "javanese",
    "kannada",
    "kazakh",
    "khmer",
    "korean",
    "lao",
    "latin",
    "latvian",
    "letzeburgesch",
    "lingala",
    "lithuanian",
    "luxembourgish",
    "macedonian",
    "malagasy",
    "malay",
    "malayalam",
    "maltese",
    "maori",
    "marathi",
    "moldavian",
    "moldovan",
    "mongolian",
    "myanmar",
    "nepali",
    "norwegian",
    "nynorsk",
    "occitan",
    "panjabi",
    "pashto",
    "persian",
    "polish",
    "portuguese",
    "punjabi",
    "pushto",
    "romanian",
    "russian",
    "sanskrit",
    "serbian",
    "shona",
    "sindhi",
    "sinhala",
    "sinhalese",
    "slovak",
    "slovenian",
    "somali",
    "spanish",
    "sundanese",
    "swahili",
    "swedish",
    "tagalog",
    "tajik",
    "tamil",
    "tatar",
    "telugu",
    "thai",
    "tibetan",
    "turkish",
    "turkmen",
    "ukrainian",
    "urdu",
    "uzbek",
    "valencian",
    "vietnamese",
    "welsh",
    "yiddish",
    "yoruba",
]

# List of supported languages by Google TL
google_Lang = {
    "auto detect": "auto",
    "afrikaans": "af",
    "albanian": "sq",
    "amharic": "am",
    "arabic": "ar",
    "armenian": "hy",
    "azerbaijani": "aze_cyrl",
    "basque": "eu",
    "belarusian": "be",
    "bengali": "bn",
    "bosnian": "bs",
    "bulgarian": "bg",
    "burmese": "my",
    "catalan:valencian": "cat",
    "cebuano": "ceb",
    "chinese (simplified)": "zh-cn",
    "chinese (simplified) - alt": "zh-CN",
    "chinese (traditional)": "zh-tw",
    "chinese (traditional) - alt": "zh-TW",
    "corsican": "co",
    "czech": "ces",
    "danish": "da",
    "dutch": "nl",
    "english": "en",
    "esperanto": "eo",
    "estonian": "et",
    "filipino (old-tagalog)": "tl",
    "finnish": "fi",
    "french": "fr",
    "galician": "gl",
    "georgian": "ka",
    "german": "de",
    "greek": "el",
    "gujarati": "gu",
    "haitian": "ht",
    "hebrew": "iw",
    "hindi": "hi",
    "hungarian": "hu",
    "icelandic": "is",
    "indonesian": "id",
    "irish": "ga",
    "italian": "it",
    "japanese": "ja",
    "javanese": "jw",
    "kannada": "kn",
    "kazakh": "kk",
    "khmer": "km",
    "korean": "ko",
    "korean vertical": "ko",
    "kurdish": "ku",
    "lao": "lo",
    "latin": "la",
    "latvian": "lv",
    "lithuanian": "lt",
    "luxembourgish": "lb",
    "macedonian": "mk",
    "malay": "ms",
    "malayalam": "ml",
    "maltese": "mt",
    "maori": "mi",
    "marathi": "mr",
    "mongolian": "mn",
    "nepali": "ne",
    "norwegian": "no",
    "persian": "fa",
    "polish": "pl",
    "portuguese": "pt",
    "punjabi": "pa",
    "romanian": "ro",
    "russian": "ru",
    "serbian": "sr",
    "spanish": "es",
    "sundanese": "su",
    "swahili": "sw",
    "swedish": "sv",
    "tajik": "tg",
    "tamil": "ta",
    "tatar": "tt",
    "telugu": "te",
    "thai": "th",
    "turkish": "tr",
    "ukrainian": "uk",
    "urdu": "ur",
    "uzbek": "uz",
    "vietnamese": "vi",
    "welsh": "cy",
    "yiddish": "yi",
    "yoruba": "yo",
}

# List of supported languages by libreTranslate
libre_Lang = {
    "auto detect": "auto",
    "arabic": "ar",
    "chinese (simplified)": "zh",
    "chinese (traditional)": "zh",
    "dutch": "nl",
    "english": "en",
    "finnish": "fi",
    "french": "fr",
    "german": "de",
    "hindi": "hi",
    "hungarian": "hu",
    "indonesian": "id",
    "irish": "ga",
    "italian": "it",
    "japanese": "ja",
    "korean": "ko",
    "polish": "pl",
    "portuguese": "pt",
    "russian": "ru",
    "spanish": "es",
    "swedish": "sv",
    "turkish": "tr",
    "ukrainian": "uk",
    "vietnamese": "vi",
}

gLang_target = list(google_Lang.keys()) 
gLang_target.pop(0)

libre_target = list(libre_Lang.keys())
libre_target.pop(0)

# select engine
engine_select_target_dict = {
    "Whisper": ["english"],
    "Google": gLang_target,
    "LibreTranslate": libre_target,
}
